spring.application.name=mihaifade-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mihaifade}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

app.owner.email=${OWNER_EMAIL}
app.owner.password=${OWNER_PASSWORD}
app.owner.first-name=${OWNER_FIRST_NAME:Mihai}
app.owner.last-name=${OWNER_LAST_NAME:Fade}

app.google.client-id=${GOOGLE_CLIENT_ID}

spring.config.import=optional:file:.env[.properties]

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}