spring.application.name=mihaifade-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mihaifade
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=***REMOVED***
app.jwt.expiration=86400000

app.owner.email=${OWNER_EMAIL:mihai@mihaifade.ro}
app.owner.password=${OWNER_PASSWORD:***REMOVED***}
app.owner.first-name=${OWNER_FIRST_NAME:Mihai}
app.owner.last-name=${OWNER_LAST_NAME:Fade}

app.google.client-id=258231621250-su7c2j8n1569q0v5jgslbd7ldvtttvd4.apps.googleusercontent.com
